import MentuExecutionGraphCore
import Testing

@Suite("Public core surface")
struct PublicSurfaceTests {
    @Test("every public concrete type is Sendable")
    func everyPublicConcreteTypeIsSendable() {
        requireSendable(CanonicalJSONValue.self)
        requireSendable(CanonicalJSONNumber.self)
        requireSendable(ExecutionGraphCanonicalizer.self)
        requireSendable(
            ExecutionGraphCanonicalizer.CanonicalizationError.self
        )
        requireSendable(ExecutionGraphDigest.self)
        requireSendable(MentuExecutionGraphCoreModule.self)

        requireSendable(ExecutionGraphCIRPolicy.self)
        requireSendable(ExecutionGraphStepLimits.self)
        requireSendable(MechanicalVerificationContract.self)
        requireSendable(ExecutionGraphStep.self)
        requireSendable(ExecutionGraphDefinition.self)

        requireSendable(ExecutionGraphViolation.self)
        requireSendable(StepSnapshotIdentity.self)
        requireSendable(StepStartInput.self)
        requireSendable(StepStartContext.self)
        requireSendable(CandidateGraphSource.self)
        requireSendable(RepositoryDiscoveryReference.self)
        requireSendable(CandidateToolRule.self)
        requireSendable(CandidateStepContract.self)
        requireSendable(CandidateGraphNode.self)
        requireSendable(PlannerGraphProposal.self)
        requireSendable(CandidateExecutionGraph.self)
        requireSendable(AuthFallbackBinding.self)
        requireSendable(EffectiveExecutionPolicy.self)
        requireSendable(PlanningSelections.self)
        requireSendable(PlanningConstraintView.self)
        requireSendable(PlanningPermit.self)
        requireSendable(RepositoryDiscoveryStatusSummary.self)
        requireSendable(RepositoryDiscoveryExclusion.self)
        requireSendable(RepositoryDiscoveryFileEntry.self)
        requireSendable(RepositoryDiscoverySnapshot.self)
        requireSendable(SealedExecutionPrompt.self)
        requireSendable(StepContractManifest.self)
        requireSendable(ExecutionArtifactBundle.self)
        requireSendable(ExecutionGraphLoweringReport.self)
        requireSendable(LoweredExecutionGraph.self)
        requireSendable(ExecutionGraphLowerer.self)

        requireSendable(ExecutionAuthorityEnvelope.self)
        requireSendable(QualificationCheck.self)
        requireSendable(ExecutionGraphQualificationProfileDescriptor.self)
        requireSendable(QualificationReport.self)
        requireSendable(QualificationCapturedFacts.self)
        requireSendable(QualifiedExecution.self)
        requireSendable(NoopExecutionGraphQualificationProfile.self)
        requireSendable(ExecutionGraphQualification.self)

        requireSendable(AdmissionRuntimeContext.self)
        requireSendable(AdmissionReceipt.self)
        requireSendable(AdmittedExecution.self)
        requireSendable(ExecutionGraphAdmission.self)
        requireSendable(ActivationInputLaneRecord.self)
        requireSendable(ActivationCallLaneBinding.self)
        requireSendable(StepActivationRecord.self)
        requireSendable(StepActivationOutcomeRecord.self)
        requireSendable(StepActivationParameters.self)
        requireSendable(StepActivationOutcomeParameters.self)
        requireSendable(StepActivationChain.self)
        requireSendable(AdmittedHostCallRequest.self)
        requireSendable(AdmittedHostCallResult.self)
        requireSendable(AdmittedHostCallResult.Termination.self)

        requireSendable(GraphSchedulerReasonID.self)
        requireSendable(ExecutionDAG.self)
        requireSendable(ExecutionDAG.Node.self)
        requireSendable(ExecutionDAG.Node.DispatchMode.self)
        requireSendable(GraphNodeState.self)
        requireSendable(GraphFailurePolicy.self)
        requireSendable(GraphStepActivation.self)
        requireSendable(GraphStepOutcome.self)
        requireSendable(GraphScheduleResult.self)
        requireSendable(GraphSchedulerEvent.self)
        requireSendable(GraphSchedulerEvent.Kind.self)
        requireSendable(NoOpGraphSchedulerEventSink.self)
        requireSendable(ExecutionGraphScheduler.self)

        requireSendable(ExecutionGraphLifecyclePhase.self)
        requireSendable(ExecutionGraphLifecycleState.self)
        requireSendable(ExecutionGraphLifecycleDetail.self)
        requireSendable(ExecutionGraphLifecycleEvent.self)
        requireSendable(ExecutionGraphLifecycleSpan.self)
        requireSendable(ExecutionGraphLifecycleReporter.self)

        requireSendable(SystemExecutionGraphClock.self)
        requireSendable(FixedExecutionGraphClock.self)
        requireSendable(SystemExecutionGraphMonotonicClock.self)
        requireSendable(NoopExecutionGraphEventSink.self)
        requireSendable(NoopStepActivationSink.self)
        requireSendable(InMemoryExecutionGraphEventSink.self)
        requireSendable(InMemoryStepActivationSink.self)
    }

    private func requireSendable<T: Sendable>(_: T.Type) {}
}
